[package]
name = "blaze"
version = "0.1.0"
edition = "2021"
resolver = "1"

[lib]
crate-type = ["cdylib"]

[features]
default = ["arrow/ffi", "datafusion/simd", "tokio/rt-multi-thread"]

[dependencies]
arrow = "24.0.0"
backtrace = "0.3.65"
datafusion = "13.0.0"
futures = "0.3"
jni = "0.19.0"
log = "0.4.14"
once_cell = "1.11.0"
panic-message = "0.3.0"
paste = "1.0.7"
prost = "0.11.0"
simplelog = "0.12.0"
tokio = "1.19"

[dependencies.datafusion-ext]
path = "../datafusion-ext"

[dependencies.plan-serde]
path = "../plan-serde"
